export const FETCH_NOTE_PENDING = "FETCH_NOTE_PENDING";
export const FETCH_NOTE_FULFILLED = "FETCH_NOTE_FULFILLED";
export const FETCH_NOTE_REJECTED = "FETCH_NOTE_REJECTED";

export const ADD_NOTE_PENDING = "ADD_NOTE_PENDING";
export const ADD_NOTE_FULFILLED = "ADD_NOTE_FULFILLED";
export const ADD_NOTE_REJECTED = "ADD_NOTE_REJECTED";

export const EDIT_NOTE_PENDING = "EDIT_NOTE_PENDING";
export const EDIT_NOTE_FULFILLED = "EDIT_NOTE_FULFILLED";
export const EDIT_NOTE_REJECTED = "EDIT_NOTE_REJECTED";

export const REMOVE_NOTE_PENDING = "REMOVE_NOTE_PENDING";
export const REMOVE_NOTE_FULFILLED = "REMOVE_NOTE_FULFILLED";
export const REMOVE_NOTE_REJECTED = "REMOVE_NOTE";

export const TOGGLE_GRID = "TOGGLE_GRID";